name: Deploy to AWS Lambda

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Install dependencies
      env:
        CI: true
      run: npm ci


