name: Deploy to AWS Lambda

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: me-central-1 # Replace with your AWS region

    # Step 5: Package and Deploy Lambda Function
    - name: Package and deploy to Lambda
      run: |
        zip -r lambda-function.zip . # Create a ZIP file of the code
        aws lambda update-function-code \
          --function-name email-security-handler \
          --zip-file fileb://lambda-function.zip
